import { TargetRepo } from './types'

export const TARGET_REPOS: TargetRepo[] = [
  {
    id: 'decisionjam',
    name: 'BloomTech-Labs/decisionjam',
    forkUrl: 'https://github.com/quiet-node/decisionjam',
    localPath: 'workspace/decisionjam',
    file: 'server/Payments.js',
    line: 58,
    snippet: 'subscriptionEndDate: subscription.current_period_end',
    expectedVerdict: 'genuine',
  },
  {
    id: 'stripe-subscriptions',
    name: 'bdcorps/stripe-subscriptions-nodejs',
    forkUrl: 'https://github.com/quiet-node/stripe-subscriptions-nodejs',
    localPath: 'workspace/stripe-subscriptions',
    file: 'app.js',
    line: 214,
    snippet: 'user.endDate = new Date(data.current_period_end * 1000)',
    expectedVerdict: 'genuine',
  },
  {
    id: 'chatbotkit',
    name: 'chatbotkit/template-nextjs-slack-agent-platform-js',
    forkUrl: 'https://github.com/quiet-node/template-nextjs-slack-agent-platform-js',
    localPath: 'workspace/chatbotkit',
    file: 'lib/billing.js',
    line: 51,
    snippet: 'return (b.current_period_end || 0) - (a.current_period_end || 0)',
    expectedVerdict: 'genuine',
  },
  {
    id: 'netflix-clone',
    name: 'aayushjainx/Netflix-Clone',
    forkUrl: 'https://github.com/quiet-node/Netflix-Clone',
    localPath: 'workspace/netflix-clone',
    file: 'src/App.js',
    line: 48,
    snippet: 'current_period_end: subscription.data().current_period_end.seconds,',
    expectedVerdict: 'false-positive',
  },
  {
    id: 'domain-estimator',
    name: 'ryanmaule/domain-value-estimator',
    forkUrl: 'https://github.com/quiet-node/domain-value-estimator',
    localPath: 'workspace/domain-estimator',
    file: 'api/db.js',
    line: 19,
    snippet: 'current_period_end INTEGER,',
    expectedVerdict: 'false-positive',
  },
]
